services:
  # ── AI CORE (FastAPI + ML) ──
#  ai-service:
#    build: 
#      context: ./Aiservice
#    container_name: vortex-ai
#    env_file: ./Aiservice/.env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - redis
#      - qdrant
#    networks:
#      - rag-net

  # ── INTEGRATION LAYER (ExpressJS) ──
  backend:
    build:
      context: ./Backend
    container_name: vortex-backend
    env_file: ./Backend/.env
    ports:
      - "5000:5000"
#    depends_on:
#      - ai-service
    networks:
      - rag-net

  # ── USER INTERFACE (React + Tailwind) ──
  frontend:
    build:
      context: ./Frontend
    container_name: vortex-frontend
    ports:
      - "8080:80"
    networks:
      - rag-net

  # ── VECTOR STORE ──
  qdrant:
    image: qdrant/qdrant:latest
    container_name: vortex-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-net

  # ── CACHE LAYER ──
  redis:
    image: redis:7-alpine
    container_name: vortex-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge

volumes:
  qdrant_storage:
